; ================== AUTO UPDATER ==================
CurrentVersion := "1.2"

VersionURL   := "https://raw.githubusercontent.com/ZxcFresk/AdminBinder/b9e24eeebcb87d783f8bd23a7471c04578c008a8/update/version.txt"
ChangelogURL := "https://raw.githubusercontent.com/ZxcFresk/AdminBinder/b9e24eeebcb87d783f8bd23a7471c04578c008a8/update/changelog.txt"
ScriptURL    := "https://raw.githubusercontent.com/ZxcFresk/AdminBinder/refs/heads/main/update/AFK_S2A.ahk"

TempVer  := A_Temp "\ver.txt"
TempLog  := A_Temp "\log.txt"

UrlDownloadToFile, %VersionURL%, %TempVer%
FileRead, OnlineVersion, %TempVer%
OnlineVersion := Trim(OnlineVersion)

if (OnlineVersion != CurrentVersion)
{
    UrlDownloadToFile, %ChangelogURL%, %TempLog%
    FileRead, ChangeLog, %TempLog%

    MsgBox, 64, Обновление %OnlineVersion%,
    (
Доступна новая версия!

Текущая: %CurrentVersion%
Новая: %OnlineVersion%

Изменения:
%ChangeLog%

Обновление будет выполнено сейчас.
    )

    UrlDownloadToFile, %ScriptURL%, %A_ScriptFullPath%
    MsgBox, 64, Готово, Обновление установлено. Скрипт перезапустится.
    Reload
}

IniRead, LastSeenVer, %A_AppData%\AdminBinder.ini, Update, Seen, 0

if (LastSeenVer != CurrentVersion)
{
    MsgBox, 64, Что нового,
    (
%ChangeLog%
    )
    IniWrite, %CurrentVersion%, %A_AppData%\AdminBinder.ini, Update, Seen
}

; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Picture, x-2 y-4 w900 h601, ./img/Madman.jpg 
Gui Add, Button, x10 y200 w113 h33 gOpenDesc, Описание
Gui Add, Button, x10 y230 w113 h33 gOpenInfo, Информация
Gui Add, Button, x10 y260 w113 h33 gOpenCmd, Команды
Gui Add, Button, x10 y290 w113 h33 gOpenNorm, Норма
Gui Add, Button, x10 y320 w113 h33 gOpenAns, Ответы
Gui Add, Button, x10 y350 w113 h33 gOpenTP, Телепорты

Gui Add, Link,x0 y390,ㅤЖалобы на админов <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8E.49/">Aleksei Dekov</a>
Gui Add, Link,x0 y410,ㅤЖалобы на госс <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D1%81%D0%BB%D1%83%D0%B6%D0%B0%D1%89%D0%B8%D1%85.52/">Aleksei Dekov</a>
Gui Add, Link,x0 y430,ㅤЖалобы на крайм <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%BE%D0%B2-%D0%BA%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80.53/">Aleksei Dekov</a>
Gui Add, Link,x0 y450,ㅤЖалобы на нефрак <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%BD%D0%B5%D1%84%D1%80%D0%B0%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%BE%D0%B2.51/">Aleksei Dekov</a>

Gui Color, FFFFFF
Gui Show, x0 y390

; Правый блок кнопок
Gui Add, Button, x450 y500 w138 h37 +Default, Сохранить
Gui Add, Button, x600 y500 w138 h37 +Default gReloadScript, Перезапустить
Gui Add, Button, x750 y500 w138 h37 +Default gCloseScript, Закрыть
Gui Add, Text, x10 y480 w200 h20 +0x200, Шкала показывает: Выполнено
Gui Add, Text, x10 y500 w200 h20 +0x200, Норма администратора(250)
Gui Add, Progress, w200 Range0-250 cGreen vMyProgress, %WeekANS%

IniRead, vupd, %a_temp%/verlen.ini, UPD, v

Gui -MaximizeBox
Gui Show, w900 h590, Admin-Binder Aleksei Dekov
Gui Color, FFFFFF
Gui Show, w900 h600
Gui Font, c0x00FF00
SoundPlay, %A_ScriptDir%\img\1209.mp3

Gui Show, w898 h597, Aleksei Dekov AHK
Return      ; ← ОЧЕНЬ ВАЖНО! Останавливает автозапуск следующих блоков


; ========================  ОКНА  ========================

OpenDesc:
    MsgBox, 0, Описание,
    (
Софт создан для облегчения работы администрации проекта Radmir S2 Role Play.

О софте: Софт обширен и универсален. Он поможет в обучении и началу админского опыта,
памятки содержат нормы наказаний и частые нарушения.

"Команды" - содержат популярные команды и поясняют, для чего они нужны.
Краткие ответы помогут в освоении функционала.

    )
Return

OpenInfo:
    MsgBox, 0, Информация,
    (
Биндер облегчит работу администрации на Radmir S2 Role Play.`n`nУдаление горячих клавишь происходит на Backspace, после создания "Bind'a" необходимо сохранение, как и после его снятия!`n`nПерезапуск биндера возможен при нажатии на "Перезапустить", Закрывать скрип только на кнопку "Закрыть", в противном случае он уйдёт в фоновые процессы!`nВо всех случаях Ctrl + F9 перезапустит работу скрипта, а Ctrl + F10 завершит работу скрипта!
    )
Return

OpenCmd:
    MsgBox, 0, Команды,
    (
⋙ ⋙ ⋙ ⋙ ⋙ ⋙Сокращение популярных команд.⋘ ⋘ ⋘ ⋘ ⋘ ⋘  - юфофшд - Пропись /ajail.`n - юьгеумщшсу - Пропись /mutevoice.`n - юьгеушс - Пропись /muteic.`n - юьгеущщс - Пропись /muteooc.`n - юцфкт - Пропись /warn.`n - юифт - Пропись /ban.`n - юпрмур - Пропись /ghveh.`n - юпр - Пропись /gh.`n - юзь - Пропись /pm.`n - ювех - Пропись /veh.`n - юпщ - Пропись /go.`n
    )
Return

OpenNorm:
    MsgBox, 0, Норма,
    (
Норма Админов-Хелперов, `n ✅ Хелперы - 100+ в неделю.`n ✅ Администраторы - 250+ в неделю.
    )
Return

OpenAns:
    MsgBox, 0, Ответы,
    (
.
    )
Return

OpenTP:
    MsgBox, 0, Телепорты,
    (
Телепорты на гос структуры:
 .LSPD - телепорт на LSPD`n .LSMC - телепорт на Больницу LSMC`n .SSMC - телепорт на Больницу SSMC`n .NG - телепорт на SANG`n .GOV - телепорт на GOV`n .FIB - телепорт на ФИБ`n `n
    )
Return


; ========================  Команды  ==========================
:?:юьгеумщшсу::
    Clipboard := "/mutevoice"
    Send, ^v
    Clipboard := ""
Return

:?:юьгеушс::
    Clipboard := "/muteic"
    Send, ^v
    Clipboard := ""
Return

:?:юьгеущщс::
    Clipboard := "/muteooc"
    Send, ^v
    Clipboard := ""
Return

:?:юфофшд::
    Clipboard := "/ajail"
    Send, ^v
    Clipboard := ""
Return

:?:юцфкт::
    Clipboard := "/warn"
    Send, ^v
    Clipboard := ""
Return

:?:юифт::
    Clipboard := "/ban"
    Send, ^v
    Clipboard := ""
Return

:?:юпрмур::
    Clipboard := "/ghveh"
    Send, ^v
    Clipboard := ""
Return

:?:юпр::
    Clipboard := "/gh"
    Send, ^v
    Clipboard := ""
Return

:?:юадшзм::
    Clipboard := "/flipv"
    Send, ^v
    Clipboard := ""
Return

:?:юпщ::
    Clipboard := "/go"
    Send, ^v
    Clipboard := ""
Return

:?:юпм::
    Clipboard := "/gv"
    Send, ^v
    Clipboard := ""
Return

:?:юф::
    Clipboard := "/a"
    Send, ^v
    Clipboard := ""
Return

:?:юзпм::
    Clipboard := "/pgv"
    Send, ^v
    Clipboard := ""
Return

:?:юмур::
    Clipboard := "/veh"
    Send, ^v
    Clipboard := ""
Return

:?:юзштащ::
    Clipboard := "/pinfo"
    Send, ^v
    Clipboard := ""
Return

:?:юрз::
    Clipboard := "/xp"
    Send, ^v
    Clipboard := ""
Return

:?:юфкьщгк::
    Clipboard := "/armour"
    Send, ^v
    Clipboard := ""
Return

:?:юфруфд::
    Clipboard := "/aheal"
    Send, ^v
    Clipboard := ""
Return

:?:югтсгаа::
    Clipboard := "/uncuff"
    Send, ^v
    Clipboard := ""
Return


; ========================  Тпшки  ============================
:?:.LSPD::
    Clipboard := "/tp -1113.29345703125, -823.17333984375 19.26188850492832"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.BCSD::
    Clipboard := "/tp -440.08984375, 6022.7421875 31.94927978515625"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.LSMC::
    Clipboard := "/tp 339.440185546875, -1395.4876708984375 32.50982666015625"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.SSMC::
    Clipboard := "/tp 1842.10888671875, 3668.172607421875 34.483154296875"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.NG::
    Clipboard := "/tp -1584.267333984375, 2789.11865234375 17.329519271850586"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.GOV::
    Clipboard := "/tp -542.1994018554688, -209.08056640625 38.760986328125"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.FIB::
    Clipboard := "/tp 93.45382690429688, -742.5665893554688 46.23120880126953"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return


; ========================  СЛУЖЕБНЫЕ  ========================

^F9::Reload
^F10::ExitApp

ReloadScript:
    Reload
Return

CloseScript:
    ExitApp
Return

GuiEscape:
GuiClose:
    ExitApp
Return

!1::
SendClipboardText("Здравствуйте.")
Return

!2::
SendClipboardText("Чем вам помочь?")
Return

!3::
SendClipboardText("Приятной игры :herb:")
Return

!4::
SendClipboardText("Обратитесь в F3 - Проблемы с игрой")
Return

!5::
SendClipboardText("Обратитесь в F3 - Жалоба")
Return

!6::
SendClipboardText("Обратитесь на форум, вам обязательно помогут.")
Return

!7::
SendClipboardText("Попробуйте перезайти в игру, если и это не поможет напишите в Технический раздел на нашем форуме Radmir RP GTA 5. <3")
Return

!q::
SendClipboardText("Если будут еще вопросы, обращайтесь.")
Return

!a::
SendClipboardText("Здравствуйте, иду к вам на помощь.")
Return

!w::
SendClipboardText("Не владеем такой информацией.")
Return

!s::
SendClipboardText("Помог вам. <3")
Return

; === Автоответы по ::…:: ===
::..::
SendClipboardText("Уточните ваш вопрос.")
Return

::.конты::
SendClipboardText("Контейнеры запускаются каждые 2 часа с 8:00 до 00:00 по МСК, в четное время (Пример: 10:00, 12:00, 14:00).")
Return

::.промо::
SendClipboardText("Мы не выдаем и не сообщаем промокоды. Все новинки вы можете найти в нашем офф. паблике ВК, либо дискорд канале Radmir GTA V.")
Return

::.авто::
SendClipboardText("Чтобы найти свой автомобиль откройте телефон(по умол. стрелочка вверх) -> GPS -> Имущество -> Затем нажмите на название вашего ТС, на карте поставится метка где он находится, если он в салоне, его нужно восстановить (подойти к НПС -> Нажать E -> Восстановление ТС -> Название вашего ТС.)")
Return

::.парковка::
SendClipboardText("Припарковать автомобиль можно сидя в нём: G -> Меню ТС -> Припарковать, либо около него: E -> Меню ТС -> Припарковать.")
Return

; === … и так далее для всех остальных биндов ===

; === Функция для вставки текста через буфер и Enter ===
SendClipboardText(Text) {
    ClipSaved := ClipboardAll      ; Сохраняем текущий буфер
    Clipboard := Text              ; Кладем нужный текст
    ClipWait, 0.5                  ; Ждем обновления буфера
    Send, ^v{Enter}                ; Вставляем и сразу Enter
    Sleep, 50                      ; Маленькая пауза для надежности
    Clipboard := ClipSaved         ; Восстанавливаем старый буфер
}
PgDn::
    Send, {vk54}
    Sleep, 50
    SendClipboardText("/tp -74.95462799072266, -819.4271240234375 326.1750793457031")
Return
