CurrentVersion := "1.2"

VersionURL   := "https://raw.githubusercontent.com/ZxcFresk/AdminBinder/main/update/version.txt"
ChangelogURL := "https://raw.githubusercontent.com/ZxcFresk/AdminBinder/main/update/changelog.txt"
ScriptURL    := "https://raw.githubusercontent.com/ZxcFresk/AdminBinder/main/update/AdminBinder.ahk"

TempVer := A_Temp "\ver.txt"
TempLog := A_Temp "\log.txt"

UrlDownloadToFile, %VersionURL%, %TempVer%
FileRead, OnlineVersion, %TempVer%
OnlineVersion := Trim(OnlineVersion)

if (OnlineVersion > CurrentVersion)
{
    UrlDownloadToFile, %ChangelogURL%, %TempLog%
    FileRead, ChangeLog, %TempLog%

    MsgBox, 64, Обновление %OnlineVersion%,
    (
Доступна новая версия!

Текущая: %CurrentVersion%
Новая: %OnlineVersion%

Изменения:
%ChangeLog%
    )

    UrlDownloadToFile, %ScriptURL%, %A_ScriptFullPath%
    Reload
}

; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Picture, x-2 y-4 w900 h601, ./img/Madman.jpg 
Gui Add, Button, x10 y200 w113 h33 gOpenDesc, Îïèñàíèå
Gui Add, Button, x10 y230 w113 h33 gOpenInfo, Èíôîðìàöèÿ
Gui Add, Button, x10 y260 w113 h33 gOpenCmd, Êîìàíäû
Gui Add, Button, x10 y290 w113 h33 gOpenNorm, Íîðìà
Gui Add, Button, x10 y320 w113 h33 gOpenAns, Îòâåòû
Gui Add, Button, x10 y350 w113 h33 gOpenTP, Òåëåïîðòû

Gui Add, Link,x0 y390,?Æàëîáû íà àäìèíîâ <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8E.49/">Aleksei Dekov</a>
Gui Add, Link,x0 y410,?Æàëîáû íà ãîññ <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D1%81%D0%BB%D1%83%D0%B6%D0%B0%D1%89%D0%B8%D1%85.52/">Aleksei Dekov</a>
Gui Add, Link,x0 y430,?Æàëîáû íà êðàéì <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%BE%D0%B2-%D0%BA%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80.53/">Aleksei Dekov</a>
Gui Add, Link,x0 y450,?Æàëîáû íà íåôðàê <a href="https://forum.radmirv.com/forums/%D0%96%D0%B0%D0%BB%D0%BE%D0%B1%D1%8B-%D0%BD%D0%B0-%D0%BD%D0%B5%D1%84%D1%80%D0%B0%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8%D0%B3%D1%80%D0%BE%D0%BA%D0%BE%D0%B2.51/">Aleksei Dekov</a>

Gui Color, FFFFFF
Gui Show, x0 y390

; Ïðàâûé áëîê êíîïîê
Gui Add, Button, x450 y500 w138 h37 +Default, Ñîõðàíèòü
Gui Add, Button, x600 y500 w138 h37 +Default gReloadScript, Ïåðåçàïóñòèòü
Gui Add, Button, x750 y500 w138 h37 +Default gCloseScript, Çàêðûòü
Gui Add, Text, x10 y480 w200 h20 +0x200, Øêàëà ïîêàçûâàåò: Âûïîëíåíî
Gui Add, Text, x10 y500 w200 h20 +0x200, Íîðìà àäìèíèñòðàòîðà(250)
Gui Add, Progress, w200 Range0-250 cGreen vMyProgress, %WeekANS%

IniRead, vupd, %a_temp%/verlen.ini, UPD, v

Gui -MaximizeBox
Gui Show, w900 h590, Admin-Binder Aleksei Dekov
Gui Color, FFFFFF
Gui Show, w900 h600
Gui Font, c0x00FF00
SoundPlay, %A_ScriptDir%\img\1209.mp3

Gui Show, w898 h597, Aleksei Dekov AHK
Return      ; < Î×ÅÍÜ ÂÀÆÍÎ! Îñòàíàâëèâàåò àâòîçàïóñê ñëåäóþùèõ áëîêîâ


; ========================  ÎÊÍÀ  ========================

OpenDesc:
    MsgBox, 0, Îïèñàíèå,
    (
Ñîôò ñîçäàí äëÿ îáëåã÷åíèÿ ðàáîòû àäìèíèñòðàöèè ïðîåêòà Radmir S2 Role Play.

Î ñîôòå: Ñîôò îáøèðåí è óíèâåðñàëåí. Îí ïîìîæåò â îáó÷åíèè è íà÷àëó àäìèíñêîãî îïûòà,
ïàìÿòêè ñîäåðæàò íîðìû íàêàçàíèé è ÷àñòûå íàðóøåíèÿ.

"Êîìàíäû" - ñîäåðæàò ïîïóëÿðíûå êîìàíäû è ïîÿñíÿþò, äëÿ ÷åãî îíè íóæíû.
Êðàòêèå îòâåòû ïîìîãóò â îñâîåíèè ôóíêöèîíàëà.

    )
Return

OpenInfo:
    MsgBox, 0, Èíôîðìàöèÿ,
    (
Áèíäåð îáëåã÷èò ðàáîòó àäìèíèñòðàöèè íà Radmir S2 Role Play.`n`nÓäàëåíèå ãîðÿ÷èõ êëàâèøü ïðîèñõîäèò íà Backspace, ïîñëå ñîçäàíèÿ "Bind'a" íåîáõîäèìî ñîõðàíåíèå, êàê è ïîñëå åãî ñíÿòèÿ!`n`nÏåðåçàïóñê áèíäåðà âîçìîæåí ïðè íàæàòèè íà "Ïåðåçàïóñòèòü", Çàêðûâàòü ñêðèï òîëüêî íà êíîïêó "Çàêðûòü", â ïðîòèâíîì ñëó÷àå îí óéä¸ò â ôîíîâûå ïðîöåññû!`nÂî âñåõ ñëó÷àÿõ Ctrl + F9 ïåðåçàïóñòèò ðàáîòó ñêðèïòà, à Ctrl + F10 çàâåðøèò ðàáîòó ñêðèïòà!
    )
Return

OpenCmd:
    MsgBox, 0, Êîìàíäû,
    (
? ? ? ? ? ?Ñîêðàùåíèå ïîïóëÿðíûõ êîìàíä.? ? ? ? ? ?  - þôîôøä - Ïðîïèñü /ajail.`n - þüãåóìùøñó - Ïðîïèñü /mutevoice.`n - þüãåóøñ - Ïðîïèñü /muteic.`n - þüãåóùùñ - Ïðîïèñü /muteooc.`n - þöôêò - Ïðîïèñü /warn.`n - þèôò - Ïðîïèñü /ban.`n - þïðìóð - Ïðîïèñü /ghveh.`n - þïð - Ïðîïèñü /gh.`n - þçü - Ïðîïèñü /pm.`n - þâåõ - Ïðîïèñü /veh.`n - þïù - Ïðîïèñü /go.`n
    )
Return

OpenNorm:
    MsgBox, 0, Íîðìà,
    (
Íîðìà Àäìèíîâ-Õåëïåðîâ, `n ? Õåëïåðû - 100+ â íåäåëþ.`n ? Àäìèíèñòðàòîðû - 250+ â íåäåëþ.
    )
Return

OpenAns:
    MsgBox, 0, Îòâåòû,
    (
.
    )
Return

OpenTP:
    MsgBox, 0, Òåëåïîðòû,
    (
Òåëåïîðòû íà ãîñ ñòðóêòóðû:
 .LSPD - òåëåïîðò íà LSPD`n .LSMC - òåëåïîðò íà Áîëüíèöó LSMC`n .SSMC - òåëåïîðò íà Áîëüíèöó SSMC`n .NG - òåëåïîðò íà SANG`n .GOV - òåëåïîðò íà GOV`n .FIB - òåëåïîðò íà ÔÈÁ`n `n
    )
Return


; ========================  Êîìàíäû  ==========================
:?:þüãåóìùøñó::
    Clipboard := "/mutevoice"
    Send, ^v
    Clipboard := ""
Return

:?:þüãåóøñ::
    Clipboard := "/muteic"
    Send, ^v
    Clipboard := ""
Return

:?:þüãåóùùñ::
    Clipboard := "/muteooc"
    Send, ^v
    Clipboard := ""
Return

:?:þôîôøä::
    Clipboard := "/ajail"
    Send, ^v
    Clipboard := ""
Return

:?:þöôêò::
    Clipboard := "/warn"
    Send, ^v
    Clipboard := ""
Return

:?:þèôò::
    Clipboard := "/ban"
    Send, ^v
    Clipboard := ""
Return

:?:þïðìóð::
    Clipboard := "/ghveh"
    Send, ^v
    Clipboard := ""
Return

:?:þïð::
    Clipboard := "/gh"
    Send, ^v
    Clipboard := ""
Return

:?:þàäøçì::
    Clipboard := "/flipv"
    Send, ^v
    Clipboard := ""
Return

:?:þïù::
    Clipboard := "/go"
    Send, ^v
    Clipboard := ""
Return

:?:þïì::
    Clipboard := "/gv"
    Send, ^v
    Clipboard := ""
Return

:?:þô::
    Clipboard := "/a"
    Send, ^v
    Clipboard := ""
Return

:?:þçïì::
    Clipboard := "/pgv"
    Send, ^v
    Clipboard := ""
Return

:?:þìóð::
    Clipboard := "/veh"
    Send, ^v
    Clipboard := ""
Return

:?:þçøòàù::
    Clipboard := "/pinfo"
    Send, ^v
    Clipboard := ""
Return

:?:þðç::
    Clipboard := "/xp"
    Send, ^v
    Clipboard := ""
Return

:?:þôêüùãê::
    Clipboard := "/armour"
    Send, ^v
    Clipboard := ""
Return

:?:þôðóôä::
    Clipboard := "/aheal"
    Send, ^v
    Clipboard := ""
Return

:?:þãòñãàà::
    Clipboard := "/uncuff"
    Send, ^v
    Clipboard := ""
Return


; ========================  Òïøêè  ============================
:?:.LSPD::
    Clipboard := "/tp -1113.29345703125, -823.17333984375 19.26188850492832"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.BCSD::
    Clipboard := "/tp -440.08984375, 6022.7421875 31.94927978515625"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.LSMC::
    Clipboard := "/tp 339.440185546875, -1395.4876708984375 32.50982666015625"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.SSMC::
    Clipboard := "/tp 1842.10888671875, 3668.172607421875 34.483154296875"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.NG::
    Clipboard := "/tp -1584.267333984375, 2789.11865234375 17.329519271850586"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.GOV::
    Clipboard := "/tp -542.1994018554688, -209.08056640625 38.760986328125"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return

:?:.FIB::
    Clipboard := "/tp 93.45382690429688, -742.5665893554688 46.23120880126953"
    Send, ^v
    Send, {Enter}
    Clipboard := ""
Return


; ========================  ÑËÓÆÅÁÍÛÅ  ========================

^F9::Reload
^F10::ExitApp

ReloadScript:
    Reload
Return

CloseScript:
    ExitApp
Return

GuiEscape:
GuiClose:
    ExitApp
Return

!1::
SendClipboardText("Çäðàâñòâóéòå.")
Return

!2::
SendClipboardText("×åì âàì ïîìî÷ü?")
Return

!3::
SendClipboardText("Ïðèÿòíîé èãðû :herb:")
Return

!4::
SendClipboardText("Îáðàòèòåñü â F3 - Ïðîáëåìû ñ èãðîé")
Return

!5::
SendClipboardText("Îáðàòèòåñü â F3 - Æàëîáà")
Return

!6::
SendClipboardText("Îáðàòèòåñü íà ôîðóì, âàì îáÿçàòåëüíî ïîìîãóò.")
Return

!7::
SendClipboardText("Ïîïðîáóéòå ïåðåçàéòè â èãðó, åñëè è ýòî íå ïîìîæåò íàïèøèòå â Òåõíè÷åñêèé ðàçäåë íà íàøåì ôîðóìå Radmir RP GTA 5. <3")
Return

!q::
SendClipboardText("Åñëè áóäóò åùå âîïðîñû, îáðàùàéòåñü.")
Return

!a::
SendClipboardText("Çäðàâñòâóéòå, èäó ê âàì íà ïîìîùü.")
Return

!w::
SendClipboardText("Íå âëàäååì òàêîé èíôîðìàöèåé.")
Return

!s::
SendClipboardText("Ïîìîã âàì. <3")
Return

; === Àâòîîòâåòû ïî :::: ===
::..::
SendClipboardText("Óòî÷íèòå âàø âîïðîñ.")
Return

::.êîíòû::
SendClipboardText("Êîíòåéíåðû çàïóñêàþòñÿ êàæäûå 2 ÷àñà ñ 8:00 äî 00:00 ïî ÌÑÊ, â ÷åòíîå âðåìÿ (Ïðèìåð: 10:00, 12:00, 14:00).")
Return

::.ïðîìî::
SendClipboardText("Ìû íå âûäàåì è íå ñîîáùàåì ïðîìîêîäû. Âñå íîâèíêè âû ìîæåòå íàéòè â íàøåì îôô. ïàáëèêå ÂÊ, ëèáî äèñêîðä êàíàëå Radmir GTA V.")
Return

::.àâòî::
SendClipboardText("×òîáû íàéòè ñâîé àâòîìîáèëü îòêðîéòå òåëåôîí(ïî óìîë. ñòðåëî÷êà ââåðõ) -> GPS -> Èìóùåñòâî -> Çàòåì íàæìèòå íà íàçâàíèå âàøåãî ÒÑ, íà êàðòå ïîñòàâèòñÿ ìåòêà ãäå îí íàõîäèòñÿ, åñëè îí â ñàëîíå, åãî íóæíî âîññòàíîâèòü (ïîäîéòè ê ÍÏÑ -> Íàæàòü E -> Âîññòàíîâëåíèå ÒÑ -> Íàçâàíèå âàøåãî ÒÑ.)")
Return

::.ïàðêîâêà::
SendClipboardText("Ïðèïàðêîâàòü àâòîìîáèëü ìîæíî ñèäÿ â í¸ì: G -> Ìåíþ ÒÑ -> Ïðèïàðêîâàòü, ëèáî îêîëî íåãî: E -> Ìåíþ ÒÑ -> Ïðèïàðêîâàòü.")
Return

; ===  è òàê äàëåå äëÿ âñåõ îñòàëüíûõ áèíäîâ ===

; === Ôóíêöèÿ äëÿ âñòàâêè òåêñòà ÷åðåç áóôåð è Enter ===
SendClipboardText(Text) {
    ClipSaved := ClipboardAll      ; Ñîõðàíÿåì òåêóùèé áóôåð
    Clipboard := Text              ; Êëàäåì íóæíûé òåêñò
    ClipWait, 0.5                  ; Æäåì îáíîâëåíèÿ áóôåðà
    Send, ^v{Enter}                ; Âñòàâëÿåì è ñðàçó Enter
    Sleep, 50                      ; Ìàëåíüêàÿ ïàóçà äëÿ íàäåæíîñòè
    Clipboard := ClipSaved         ; Âîññòàíàâëèâàåì ñòàðûé áóôåð
}
PgDn::
    Send, {vk54}
    Sleep, 50
    SendClipboardText("/tp -74.95462799072266, -819.4271240234375 326.1750793457031")

Return
